### ISSUE TITLE
clear tempdir directories when finished?

### ISSUE THREAD

**Issue by mpadge** [r-lib/callr#104]
This is really a `processx` issue, but easier to describe here: `callr::r_bg()` creates one or more new `/tmp/Rtmp*` directories (on *nix, other equivalents on other ODs) each time it is called, and these are left semi-permanently. It should be fairly easy to remove them one the `processx` process is exited. Would that be possible, please?

Motivation: It is not uncommon to need to examine the contents of `tempdir()` outside R, yet this becomes very difficult when there are hundreds of `/tmp/Rtmp*` directories created by exited `processx` instances that have not cleaned these up.

**Comment by gaborcsardi** [comment]
Do you want to submit a PR?

**Comment by mpadge** [comment]
... with help, maybe. I've no idea where such a functionality would best be placed. The primary function to close connections seems to be [`process_x_connection_close`](https://github.com/r-lib/processx/blob/master/src/processx-connection.c#L622-L634), but that's obviously not the place to do any `tempdir` cleanups. My guess would be somewhere in [`src/unix/processx_finalizer`](https://github.com/r-lib/processx/blob/master/src/unix/processx.c#L201-L233) for the unix case, and equivalent for windows?

**Comment by gaborcsardi** [comment]
I think this has to be in callr, probably, because processx does not create any temporary files. processx also cannot clean up any file that are used for stdout/stderr or other purposes, because it does not know if these files are needed.

It seems that callr creates the following temp files currently, in `setup.R`:
- [ ] function file
- [ ] result file
- [ ] script file
- [ ] system profile
- [ ] user profile
- [ ] system environment file
- [ ] user environment file

in `r-session.R`:
- [ ] result file
- [ ] output file
- [ ] error file

in `package.R`:
- [ ] env file

**Comment by mpadge** [comment]
Great fix - thanks @gaborcsardi

**Comment by tabulez** [comment]
I'm noticing this issue in the context of using vscode-R on a linux server. When VSCode is closed without formally quitting R or disconnecting from the server, Rtmp directories remain. 

**To Reproduce**
- SSH into a remote server via putty and remove any existing Rtmp directories
- With vscode, open test.R that has the line: print("hello world")
- Close vscode after running the line. I noticed two new Rtmp directories in /tmp that remained.
- In putty, run R, print("hello world") q(). No new Rtmp directories were added. Same happens if I use "Rscript test.R"
- If I repeat step 2, I notice 2 new directories in /tmp are created that aren't removed after closing vscode.

**Output**
- The files and directories generated in the example look like this: 
```
./RtmpkpecfE:
total 334K
callr-client--eff06ee.so
callr-env-4e74108faaf5
callr-fun-4e747d5c0b79
callr-res-4e7435f83e09
callr-scr-4e74584134a4
callr-sev-4e742c3c1549
callr-sev-4e744c22c3
callr-sev-4e744d2e7ca0
callr-sev-4e74531de39e
callr-sev-4e7463f7c62a
callr-spr-4e7418ba6840
callr-spr-4e741d41d3da
callr-spr-4e74606cd5c9
callr-spr-4e74748293fd
callr-spr-4e74c871bcd
callr-uev-4e74316db898
callr-uev-4e74480eebcf
callr-uev-4e74503ac808
callr-uev-4e74a9da0d6
callr-uev-4e74d3cfc3d
callr-upr-4e7418eb6e65
callr-upr-4e74433f3810
callr-upr-4e744509737a
callr-upr-4e74692e206a
callr-upr-4e74f103836

./RtmpwTGjlB:
total 83K
libloc_180_124706c06bfefeeb.rds
libloc_180_dbd70c741b94b12c.rds
libloc_215_684dcd0b7abed33c.rds
```

**Environment**
- OS: Linux CentOS 7
- VSCode Version: 1.86
- R Version: 3.6.0
- vscode-R version: 2.8.2
- language server version = 0.3.16
- callr = 3.7.3
