### ISSUE TITLE
memory limit error in the subprocess of callr:r

### ISSUE THREAD

**Issue by earthcli** [r-lib/callr#159]
callr is a very usefull package that usually I use it to start a new sub session for saving memory, and thank you all for your efforts working on it.

I have generally two questions about how to work with it well,

1. Is there a parameter for setting the memory.limit() in callr::r? I have met an error about memory in a subprocess, I have checked that the memory.size() in callr:r is only 36.2, while it is 652 outside callr:r. 
except for setting the memory.limit() in the function, is there a parameter could be set?

2.whether I can pass a global variables to the callr:r ? or can I tell the callr:r to load a package?

Thanks.

**Comment by gaborcsardi** [comment]
Hi, I am not very familiar with 32 bit Windows, but it seems from `?memory.limit` that there is an environment variables that you can set and there is also a command line argument. Both can be set by `callr::r()`, see the `env` and the `cmdargs` arguments.

**Comment by gaborcsardi** [comment]
Just realized that I missed your second question. 

It does not make too much sense to set a global variable in `callr::r()` because it will not be there the next time, since every `callr:r()` starts a new subprocess. If you want a persistent subprocess, `r_session` is better. 

You can set a global variable in `r_session` directly, i.e. with `assign("symbol", value, envir = .GlobalEnv)`, within the function that you pass to `callr::r()` or the `r_session$run()` method, add pass `value` as an argument to the function.

Similarly, to load a package, just load it within the function, as usual. E.g. to load callr itself:

```r
callr::r(function() { library("callr"); loadedNamespaces() }
```
