### ISSUE TITLE
Support tryCatch & better documentation for error argument to r_bg

### ISSUE THREAD

**Issue by yogat3ch** [r-lib/callr#176]
Hi `callr` devs,
Was just experimenting with backgrounding a long running process with `r_bg` and came to realize that `tryCatch` doesn't function in the expected way when using `  r_bg`. Any errors caught by tryCatch still surface and interrupt the background process it appears:

Here's a reprex that should run for 60s and message the errors
```

fun <- rlang::as_function(~{
  i <- 1
  message("start")
  while(i < 60) {
    message(i)
    i <- i + 1
    if (i %% 2 == 0) stop("divide by")
    Sys.sleep(1)
  }
})
bg <- callr::r_bg(rlang::as_function(~{
  tryCatch(.x(), error = function(e) {message(e);NULL})
}), args = list(.x = fun))
bg$is_alive()
bg$get_result()
```

I looked into the `error` argument to `r_bg` in an attempt to remedy the issue. The doc indicates "See details below." but I did not find any further information. 

Any ideas for remedying this?

**Comment by gaborcsardi** [comment]
That's not how `tryCatch()` works, though. Your loop will not just keep running if the error is caught outside of the loop. For that you need to put the `tryCatch()` inside the loop. This has nothing to do with callr:

```r
❯ tryCatch(fun(), error = function(e) e)
start
1
<simpleError in fun(): divide by>
```

Also, `bg$get_result()` errors, because you re-throw the caught condition with `message()`. So callr's own `tryCatch()` will catch this because it has an `error` class. Throw a new message instead, with the same message, if you want to turn the error into a message. Or remove the `error` class:

```r
bg <- callr::r_bg(rlang::as_function(~{
  tryCatch(.x(), error = function(e) { message(e$message); "done" })
}), args = list(.x = fun))
bg$wait()
bg$get_result()
#> [1] "done"
```

**Comment by yogat3ch** [comment]
>bg$get_result() errors, because you re-throw the caught condition with message()

That's it! My bad, thanks for the tip and the solution!
